# PopOS system config
tap 'homebrew/services' # service manager

# Text editors
brew 'nvim'

# Programming lanaguages, language-specific package managers, and source control
brew 'dep'
brew 'gcc'
brew 'git'
brew 'go'

# Shell environment - then oh-my-zsh is installed afterwards
brew "zsh-autosuggestions"
brew 'zsh-syntax-highlighting'

# CLI utilities / debugging
brew 'curl'
brew 'jq'
brew 'yq'

# the "cloud"
brew 'kubernetes-cli'
brew 'terraform'
brew 'terraform-docs'

# Support for installing casks (desktop applications/3rd-party repos)
#tap 'homebrew/cask' # install applications via Homebrew
#brew 'cask'

## Terminal, window manager and hotkey-daemon
#cask 'kitty'
#cask 'sublime-text'
#cask 'google-cloud-sdk'
#cask 'docker'
#cask 'ngrok'
#cask 'google-chrome'
#cask 'spotify'
#cask 'viscosity'
#cask 'vlc'
#cask 'discord'
#cask 'steam'
